---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trendscope-frontend
  namespace: trendscope
  labels:
    app.kubernetes.io/name: trendscope
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: trendscope
spec:
  replicas: 2
  
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  
  selector:
    matchLabels:
      app.kubernetes.io/name: trendscope
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: trendscope
        app.kubernetes.io/component: frontend
        app.kubernetes.io/part-of: trendscope
    spec:
      containers:
      - name: frontend
        # GitHub Container Registry の trendscope-ui イメージを使用
        image: ghcr.io/hirano00o/trendscope-ui:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        
        # 環境変数の設定（ConfigMapから全て自動読み込み）
        envFrom:
        - configMapRef:
            name: trendscope-config
        
        # リソース制限（Docker Composeの設定を参考）
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "300m"
        
        # ヘルスチェック設定
        livenessProbe:
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 40
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
          successThreshold: 1
        
        readinessProbe:
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        
        # セキュリティコンテキスト
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        
        # ボリュームマウント（Next.jsキャッシュなど）
        volumeMounts:
        - name: nextjs-cache
          mountPath: /app/.next/cache
        - name: tmp
          mountPath: /tmp
      
      # Pod レベルのセキュリティコンテキスト
      securityContext:
        fsGroup: 1000
      
      # ボリューム定義
      volumes:
      - name: nextjs-cache
        emptyDir: {}
      - name: tmp
        emptyDir: {}
