---
apiVersion: v1
kind: Service
metadata:
  name: trendscope-backend-service
  namespace: trendscope
  labels:
    app.kubernetes.io/name: trendscope
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: trendscope
  annotations:
    description: "TrendScope Backend API Service"
spec:
  type: ClusterIP  # 内部通信用
  selector:
    app.kubernetes.io/name: trendscope
    app.kubernetes.io/component: backend
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
