---
apiVersion: v1
kind: ConfigMap
metadata:
  name: trendscope-discord-bot-config
  namespace: trendscope
  labels:
    app.kubernetes.io/name: trendscope
    app.kubernetes.io/component: discord-bot-configmap
data:
  # Discord Bot configuration
  EXECUTION_MODE: "once"  # "once" for Kubernetes CronJob, "cron" for Docker Compose
  BACKEND_API_URL: "http://trendscope-backend-service:8000"
  CSV_PATH: "/data/screener_result.csv"
  CRON_SCHEDULE: "0 10 * * 1-5"  # 平日朝10時（cronモード時のみ使用）
  MAX_WORKERS: "10"
  TOP_STOCKS_COUNT: "15"
  LOG_LEVEL: "INFO"  # "DEBUG", "INFO", "WARN", "ERROR"
  
  # SQLite Database configuration
  DATABASE_PATH: "/data/db/stocks.db"
  PRICE_FILTER_ENABLED: "true"
  MIN_STOCK_PRICE: "100.0"
  MAX_STOCK_PRICE: "5000.0"
  CSV_FALLBACK_ENABLED: "true"
