---
apiVersion: v1
kind: Secret
metadata:
  name: trendscope-discord-bot-secret
  namespace: trendscope
  labels:
    app.kubernetes.io/name: trendscope
    app.kubernetes.io/component: discord-bot-secret
type: Opaque
data:
  # Discord Webhook URL (base64 encoded)
  # To create this secret:
  # echo -n "https://discord.com/api/webhooks/YOUR_WEBHOOK_URL" | base64
  # Then replace the value below
  DISCORD_WEBHOOK_URL: ""

---
# Example of how to create this secret using kubectl:
# kubectl create secret generic trendscope-discord-bot-secret \
#   --from-literal=DISCORD_WEBHOOK_URL="https://discord.com/api/webhooks/YOUR_WEBHOOK_URL" \
#   --namespace=trendscope