apiVersion: v1
kind: Service
metadata:
  name: stock-batch-metrics
  namespace: stock-batch
  labels:
    app: trendscope-stock-db-batch
    component: metrics
spec:
  clusterIP: None  # Headless service
  selector:
    app: trendscope-stock-db-batch
  ports:
  - name: metrics
    port: 8000
    targetPort: 8000
---
# Prometheus ServiceMonitor (Prometheus Operator使用時)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: stock-batch-monitor
  namespace: stock-batch
  labels:
    app: trendscope-stock-db-batch
    release: prometheus
spec:
  selector:
    matchLabels:
      app: trendscope-stock-db-batch
      component: metrics
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
---